# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/lead/pico

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/lead/pico

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/lead/pico/CMakeFiles /home/lead/pico//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/lead/pico/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named main

# Build rule for target.
main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 main
.PHONY : main

# fast build rule for target.
main/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/build
.PHONY : main/fast

#=============================================================================
# Target rules for targets named ELF2UF2Build

# Build rule for target.
ELF2UF2Build: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ELF2UF2Build
.PHONY : ELF2UF2Build

# fast build rule for target.
ELF2UF2Build/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ELF2UF2Build.dir/build.make CMakeFiles/ELF2UF2Build.dir/build
.PHONY : ELF2UF2Build/fast

#=============================================================================
# Target rules for targets named bs2_default

# Build rule for target.
bs2_default: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 bs2_default
.PHONY : bs2_default

# fast build rule for target.
bs2_default/fast:
	$(MAKE) $(MAKESILENT) -f pico-sdk/src/rp2_common/boot_stage2/CMakeFiles/bs2_default.dir/build.make pico-sdk/src/rp2_common/boot_stage2/CMakeFiles/bs2_default.dir/build
.PHONY : bs2_default/fast

#=============================================================================
# Target rules for targets named bs2_default_bin

# Build rule for target.
bs2_default_bin: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 bs2_default_bin
.PHONY : bs2_default_bin

# fast build rule for target.
bs2_default_bin/fast:
	$(MAKE) $(MAKESILENT) -f pico-sdk/src/rp2_common/boot_stage2/CMakeFiles/bs2_default_bin.dir/build.make pico-sdk/src/rp2_common/boot_stage2/CMakeFiles/bs2_default_bin.dir/build
.PHONY : bs2_default_bin/fast

#=============================================================================
# Target rules for targets named bs2_default_padded_checksummed_asm

# Build rule for target.
bs2_default_padded_checksummed_asm: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 bs2_default_padded_checksummed_asm
.PHONY : bs2_default_padded_checksummed_asm

# fast build rule for target.
bs2_default_padded_checksummed_asm/fast:
	$(MAKE) $(MAKESILENT) -f pico-sdk/src/rp2_common/boot_stage2/CMakeFiles/bs2_default_padded_checksummed_asm.dir/build.make pico-sdk/src/rp2_common/boot_stage2/CMakeFiles/bs2_default_padded_checksummed_asm.dir/build
.PHONY : bs2_default_padded_checksummed_asm/fast

#=============================================================================
# Target rules for targets named PioasmBuild

# Build rule for target.
PioasmBuild: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 PioasmBuild
.PHONY : PioasmBuild

# fast build rule for target.
PioasmBuild/fast:
	$(MAKE) $(MAKESILENT) -f pico-sdk/src/rp2_common/pico_cyw43_driver/CMakeFiles/PioasmBuild.dir/build.make pico-sdk/src/rp2_common/pico_cyw43_driver/CMakeFiles/PioasmBuild.dir/build
.PHONY : PioasmBuild/fast

#=============================================================================
# Target rules for targets named cyw43_driver_picow_cyw43_bus_pio_spi_pio_h

# Build rule for target.
cyw43_driver_picow_cyw43_bus_pio_spi_pio_h: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 cyw43_driver_picow_cyw43_bus_pio_spi_pio_h
.PHONY : cyw43_driver_picow_cyw43_bus_pio_spi_pio_h

# fast build rule for target.
cyw43_driver_picow_cyw43_bus_pio_spi_pio_h/fast:
	$(MAKE) $(MAKESILENT) -f pico-sdk/src/rp2_common/pico_cyw43_driver/CMakeFiles/cyw43_driver_picow_cyw43_bus_pio_spi_pio_h.dir/build.make pico-sdk/src/rp2_common/pico_cyw43_driver/CMakeFiles/cyw43_driver_picow_cyw43_bus_pio_spi_pio_h.dir/build
.PHONY : cyw43_driver_picow_cyw43_bus_pio_spi_pio_h/fast

hooks.obj: hooks.cpp.obj
.PHONY : hooks.obj

# target to build an object file
hooks.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/hooks.cpp.obj
.PHONY : hooks.cpp.obj

hooks.i: hooks.cpp.i
.PHONY : hooks.i

# target to preprocess a source file
hooks.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/hooks.cpp.i
.PHONY : hooks.cpp.i

hooks.s: hooks.cpp.s
.PHONY : hooks.s

# target to generate assembly for a file
hooks.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/hooks.cpp.s
.PHONY : hooks.cpp.s

main.obj: main.cpp.obj
.PHONY : main.obj

# target to build an object file
main.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/main.cpp.obj
.PHONY : main.cpp.obj

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/main.cpp.s
.PHONY : main.cpp.s

opt/pico/FreeRTOS-Kernel/croutine.obj: opt/pico/FreeRTOS-Kernel/croutine.c.obj
.PHONY : opt/pico/FreeRTOS-Kernel/croutine.obj

# target to build an object file
opt/pico/FreeRTOS-Kernel/croutine.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/opt/pico/FreeRTOS-Kernel/croutine.c.obj
.PHONY : opt/pico/FreeRTOS-Kernel/croutine.c.obj

opt/pico/FreeRTOS-Kernel/croutine.i: opt/pico/FreeRTOS-Kernel/croutine.c.i
.PHONY : opt/pico/FreeRTOS-Kernel/croutine.i

# target to preprocess a source file
opt/pico/FreeRTOS-Kernel/croutine.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/opt/pico/FreeRTOS-Kernel/croutine.c.i
.PHONY : opt/pico/FreeRTOS-Kernel/croutine.c.i

opt/pico/FreeRTOS-Kernel/croutine.s: opt/pico/FreeRTOS-Kernel/croutine.c.s
.PHONY : opt/pico/FreeRTOS-Kernel/croutine.s

# target to generate assembly for a file
opt/pico/FreeRTOS-Kernel/croutine.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/opt/pico/FreeRTOS-Kernel/croutine.c.s
.PHONY : opt/pico/FreeRTOS-Kernel/croutine.c.s

opt/pico/FreeRTOS-Kernel/event_groups.obj: opt/pico/FreeRTOS-Kernel/event_groups.c.obj
.PHONY : opt/pico/FreeRTOS-Kernel/event_groups.obj

# target to build an object file
opt/pico/FreeRTOS-Kernel/event_groups.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/opt/pico/FreeRTOS-Kernel/event_groups.c.obj
.PHONY : opt/pico/FreeRTOS-Kernel/event_groups.c.obj

opt/pico/FreeRTOS-Kernel/event_groups.i: opt/pico/FreeRTOS-Kernel/event_groups.c.i
.PHONY : opt/pico/FreeRTOS-Kernel/event_groups.i

# target to preprocess a source file
opt/pico/FreeRTOS-Kernel/event_groups.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/opt/pico/FreeRTOS-Kernel/event_groups.c.i
.PHONY : opt/pico/FreeRTOS-Kernel/event_groups.c.i

opt/pico/FreeRTOS-Kernel/event_groups.s: opt/pico/FreeRTOS-Kernel/event_groups.c.s
.PHONY : opt/pico/FreeRTOS-Kernel/event_groups.s

# target to generate assembly for a file
opt/pico/FreeRTOS-Kernel/event_groups.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/opt/pico/FreeRTOS-Kernel/event_groups.c.s
.PHONY : opt/pico/FreeRTOS-Kernel/event_groups.c.s

opt/pico/FreeRTOS-Kernel/list.obj: opt/pico/FreeRTOS-Kernel/list.c.obj
.PHONY : opt/pico/FreeRTOS-Kernel/list.obj

# target to build an object file
opt/pico/FreeRTOS-Kernel/list.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/opt/pico/FreeRTOS-Kernel/list.c.obj
.PHONY : opt/pico/FreeRTOS-Kernel/list.c.obj

opt/pico/FreeRTOS-Kernel/list.i: opt/pico/FreeRTOS-Kernel/list.c.i
.PHONY : opt/pico/FreeRTOS-Kernel/list.i

# target to preprocess a source file
opt/pico/FreeRTOS-Kernel/list.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/opt/pico/FreeRTOS-Kernel/list.c.i
.PHONY : opt/pico/FreeRTOS-Kernel/list.c.i

opt/pico/FreeRTOS-Kernel/list.s: opt/pico/FreeRTOS-Kernel/list.c.s
.PHONY : opt/pico/FreeRTOS-Kernel/list.s

# target to generate assembly for a file
opt/pico/FreeRTOS-Kernel/list.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/opt/pico/FreeRTOS-Kernel/list.c.s
.PHONY : opt/pico/FreeRTOS-Kernel/list.c.s

opt/pico/FreeRTOS-Kernel/portable/MemMang/heap_4.obj: opt/pico/FreeRTOS-Kernel/portable/MemMang/heap_4.c.obj
.PHONY : opt/pico/FreeRTOS-Kernel/portable/MemMang/heap_4.obj

# target to build an object file
opt/pico/FreeRTOS-Kernel/portable/MemMang/heap_4.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/opt/pico/FreeRTOS-Kernel/portable/MemMang/heap_4.c.obj
.PHONY : opt/pico/FreeRTOS-Kernel/portable/MemMang/heap_4.c.obj

opt/pico/FreeRTOS-Kernel/portable/MemMang/heap_4.i: opt/pico/FreeRTOS-Kernel/portable/MemMang/heap_4.c.i
.PHONY : opt/pico/FreeRTOS-Kernel/portable/MemMang/heap_4.i

# target to preprocess a source file
opt/pico/FreeRTOS-Kernel/portable/MemMang/heap_4.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/opt/pico/FreeRTOS-Kernel/portable/MemMang/heap_4.c.i
.PHONY : opt/pico/FreeRTOS-Kernel/portable/MemMang/heap_4.c.i

opt/pico/FreeRTOS-Kernel/portable/MemMang/heap_4.s: opt/pico/FreeRTOS-Kernel/portable/MemMang/heap_4.c.s
.PHONY : opt/pico/FreeRTOS-Kernel/portable/MemMang/heap_4.s

# target to generate assembly for a file
opt/pico/FreeRTOS-Kernel/portable/MemMang/heap_4.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/opt/pico/FreeRTOS-Kernel/portable/MemMang/heap_4.c.s
.PHONY : opt/pico/FreeRTOS-Kernel/portable/MemMang/heap_4.c.s

opt/pico/FreeRTOS-Kernel/portable/ThirdParty/GCC/RP2040/port.obj: opt/pico/FreeRTOS-Kernel/portable/ThirdParty/GCC/RP2040/port.c.obj
.PHONY : opt/pico/FreeRTOS-Kernel/portable/ThirdParty/GCC/RP2040/port.obj

# target to build an object file
opt/pico/FreeRTOS-Kernel/portable/ThirdParty/GCC/RP2040/port.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/opt/pico/FreeRTOS-Kernel/portable/ThirdParty/GCC/RP2040/port.c.obj
.PHONY : opt/pico/FreeRTOS-Kernel/portable/ThirdParty/GCC/RP2040/port.c.obj

opt/pico/FreeRTOS-Kernel/portable/ThirdParty/GCC/RP2040/port.i: opt/pico/FreeRTOS-Kernel/portable/ThirdParty/GCC/RP2040/port.c.i
.PHONY : opt/pico/FreeRTOS-Kernel/portable/ThirdParty/GCC/RP2040/port.i

# target to preprocess a source file
opt/pico/FreeRTOS-Kernel/portable/ThirdParty/GCC/RP2040/port.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/opt/pico/FreeRTOS-Kernel/portable/ThirdParty/GCC/RP2040/port.c.i
.PHONY : opt/pico/FreeRTOS-Kernel/portable/ThirdParty/GCC/RP2040/port.c.i

opt/pico/FreeRTOS-Kernel/portable/ThirdParty/GCC/RP2040/port.s: opt/pico/FreeRTOS-Kernel/portable/ThirdParty/GCC/RP2040/port.c.s
.PHONY : opt/pico/FreeRTOS-Kernel/portable/ThirdParty/GCC/RP2040/port.s

# target to generate assembly for a file
opt/pico/FreeRTOS-Kernel/portable/ThirdParty/GCC/RP2040/port.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/opt/pico/FreeRTOS-Kernel/portable/ThirdParty/GCC/RP2040/port.c.s
.PHONY : opt/pico/FreeRTOS-Kernel/portable/ThirdParty/GCC/RP2040/port.c.s

opt/pico/FreeRTOS-Kernel/queue.obj: opt/pico/FreeRTOS-Kernel/queue.c.obj
.PHONY : opt/pico/FreeRTOS-Kernel/queue.obj

# target to build an object file
opt/pico/FreeRTOS-Kernel/queue.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/opt/pico/FreeRTOS-Kernel/queue.c.obj
.PHONY : opt/pico/FreeRTOS-Kernel/queue.c.obj

opt/pico/FreeRTOS-Kernel/queue.i: opt/pico/FreeRTOS-Kernel/queue.c.i
.PHONY : opt/pico/FreeRTOS-Kernel/queue.i

# target to preprocess a source file
opt/pico/FreeRTOS-Kernel/queue.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/opt/pico/FreeRTOS-Kernel/queue.c.i
.PHONY : opt/pico/FreeRTOS-Kernel/queue.c.i

opt/pico/FreeRTOS-Kernel/queue.s: opt/pico/FreeRTOS-Kernel/queue.c.s
.PHONY : opt/pico/FreeRTOS-Kernel/queue.s

# target to generate assembly for a file
opt/pico/FreeRTOS-Kernel/queue.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/opt/pico/FreeRTOS-Kernel/queue.c.s
.PHONY : opt/pico/FreeRTOS-Kernel/queue.c.s

opt/pico/FreeRTOS-Kernel/stream_buffer.obj: opt/pico/FreeRTOS-Kernel/stream_buffer.c.obj
.PHONY : opt/pico/FreeRTOS-Kernel/stream_buffer.obj

# target to build an object file
opt/pico/FreeRTOS-Kernel/stream_buffer.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/opt/pico/FreeRTOS-Kernel/stream_buffer.c.obj
.PHONY : opt/pico/FreeRTOS-Kernel/stream_buffer.c.obj

opt/pico/FreeRTOS-Kernel/stream_buffer.i: opt/pico/FreeRTOS-Kernel/stream_buffer.c.i
.PHONY : opt/pico/FreeRTOS-Kernel/stream_buffer.i

# target to preprocess a source file
opt/pico/FreeRTOS-Kernel/stream_buffer.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/opt/pico/FreeRTOS-Kernel/stream_buffer.c.i
.PHONY : opt/pico/FreeRTOS-Kernel/stream_buffer.c.i

opt/pico/FreeRTOS-Kernel/stream_buffer.s: opt/pico/FreeRTOS-Kernel/stream_buffer.c.s
.PHONY : opt/pico/FreeRTOS-Kernel/stream_buffer.s

# target to generate assembly for a file
opt/pico/FreeRTOS-Kernel/stream_buffer.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/opt/pico/FreeRTOS-Kernel/stream_buffer.c.s
.PHONY : opt/pico/FreeRTOS-Kernel/stream_buffer.c.s

opt/pico/FreeRTOS-Kernel/tasks.obj: opt/pico/FreeRTOS-Kernel/tasks.c.obj
.PHONY : opt/pico/FreeRTOS-Kernel/tasks.obj

# target to build an object file
opt/pico/FreeRTOS-Kernel/tasks.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/opt/pico/FreeRTOS-Kernel/tasks.c.obj
.PHONY : opt/pico/FreeRTOS-Kernel/tasks.c.obj

opt/pico/FreeRTOS-Kernel/tasks.i: opt/pico/FreeRTOS-Kernel/tasks.c.i
.PHONY : opt/pico/FreeRTOS-Kernel/tasks.i

# target to preprocess a source file
opt/pico/FreeRTOS-Kernel/tasks.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/opt/pico/FreeRTOS-Kernel/tasks.c.i
.PHONY : opt/pico/FreeRTOS-Kernel/tasks.c.i

opt/pico/FreeRTOS-Kernel/tasks.s: opt/pico/FreeRTOS-Kernel/tasks.c.s
.PHONY : opt/pico/FreeRTOS-Kernel/tasks.s

# target to generate assembly for a file
opt/pico/FreeRTOS-Kernel/tasks.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/opt/pico/FreeRTOS-Kernel/tasks.c.s
.PHONY : opt/pico/FreeRTOS-Kernel/tasks.c.s

opt/pico/FreeRTOS-Kernel/timers.obj: opt/pico/FreeRTOS-Kernel/timers.c.obj
.PHONY : opt/pico/FreeRTOS-Kernel/timers.obj

# target to build an object file
opt/pico/FreeRTOS-Kernel/timers.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/opt/pico/FreeRTOS-Kernel/timers.c.obj
.PHONY : opt/pico/FreeRTOS-Kernel/timers.c.obj

opt/pico/FreeRTOS-Kernel/timers.i: opt/pico/FreeRTOS-Kernel/timers.c.i
.PHONY : opt/pico/FreeRTOS-Kernel/timers.i

# target to preprocess a source file
opt/pico/FreeRTOS-Kernel/timers.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/opt/pico/FreeRTOS-Kernel/timers.c.i
.PHONY : opt/pico/FreeRTOS-Kernel/timers.c.i

opt/pico/FreeRTOS-Kernel/timers.s: opt/pico/FreeRTOS-Kernel/timers.c.s
.PHONY : opt/pico/FreeRTOS-Kernel/timers.s

# target to generate assembly for a file
opt/pico/FreeRTOS-Kernel/timers.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/opt/pico/FreeRTOS-Kernel/timers.c.s
.PHONY : opt/pico/FreeRTOS-Kernel/timers.c.s

opt/pico/pico-sdk/src/common/pico_sync/critical_section.obj: opt/pico/pico-sdk/src/common/pico_sync/critical_section.c.obj
.PHONY : opt/pico/pico-sdk/src/common/pico_sync/critical_section.obj

# target to build an object file
opt/pico/pico-sdk/src/common/pico_sync/critical_section.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/opt/pico/pico-sdk/src/common/pico_sync/critical_section.c.obj
.PHONY : opt/pico/pico-sdk/src/common/pico_sync/critical_section.c.obj

opt/pico/pico-sdk/src/common/pico_sync/critical_section.i: opt/pico/pico-sdk/src/common/pico_sync/critical_section.c.i
.PHONY : opt/pico/pico-sdk/src/common/pico_sync/critical_section.i

# target to preprocess a source file
opt/pico/pico-sdk/src/common/pico_sync/critical_section.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/opt/pico/pico-sdk/src/common/pico_sync/critical_section.c.i
.PHONY : opt/pico/pico-sdk/src/common/pico_sync/critical_section.c.i

opt/pico/pico-sdk/src/common/pico_sync/critical_section.s: opt/pico/pico-sdk/src/common/pico_sync/critical_section.c.s
.PHONY : opt/pico/pico-sdk/src/common/pico_sync/critical_section.s

# target to generate assembly for a file
opt/pico/pico-sdk/src/common/pico_sync/critical_section.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/opt/pico/pico-sdk/src/common/pico_sync/critical_section.c.s
.PHONY : opt/pico/pico-sdk/src/common/pico_sync/critical_section.c.s

opt/pico/pico-sdk/src/common/pico_sync/lock_core.obj: opt/pico/pico-sdk/src/common/pico_sync/lock_core.c.obj
.PHONY : opt/pico/pico-sdk/src/common/pico_sync/lock_core.obj

# target to build an object file
opt/pico/pico-sdk/src/common/pico_sync/lock_core.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/opt/pico/pico-sdk/src/common/pico_sync/lock_core.c.obj
.PHONY : opt/pico/pico-sdk/src/common/pico_sync/lock_core.c.obj

opt/pico/pico-sdk/src/common/pico_sync/lock_core.i: opt/pico/pico-sdk/src/common/pico_sync/lock_core.c.i
.PHONY : opt/pico/pico-sdk/src/common/pico_sync/lock_core.i

# target to preprocess a source file
opt/pico/pico-sdk/src/common/pico_sync/lock_core.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/opt/pico/pico-sdk/src/common/pico_sync/lock_core.c.i
.PHONY : opt/pico/pico-sdk/src/common/pico_sync/lock_core.c.i

opt/pico/pico-sdk/src/common/pico_sync/lock_core.s: opt/pico/pico-sdk/src/common/pico_sync/lock_core.c.s
.PHONY : opt/pico/pico-sdk/src/common/pico_sync/lock_core.s

# target to generate assembly for a file
opt/pico/pico-sdk/src/common/pico_sync/lock_core.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/opt/pico/pico-sdk/src/common/pico_sync/lock_core.c.s
.PHONY : opt/pico/pico-sdk/src/common/pico_sync/lock_core.c.s

opt/pico/pico-sdk/src/common/pico_sync/mutex.obj: opt/pico/pico-sdk/src/common/pico_sync/mutex.c.obj
.PHONY : opt/pico/pico-sdk/src/common/pico_sync/mutex.obj

# target to build an object file
opt/pico/pico-sdk/src/common/pico_sync/mutex.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/opt/pico/pico-sdk/src/common/pico_sync/mutex.c.obj
.PHONY : opt/pico/pico-sdk/src/common/pico_sync/mutex.c.obj

opt/pico/pico-sdk/src/common/pico_sync/mutex.i: opt/pico/pico-sdk/src/common/pico_sync/mutex.c.i
.PHONY : opt/pico/pico-sdk/src/common/pico_sync/mutex.i

# target to preprocess a source file
opt/pico/pico-sdk/src/common/pico_sync/mutex.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/opt/pico/pico-sdk/src/common/pico_sync/mutex.c.i
.PHONY : opt/pico/pico-sdk/src/common/pico_sync/mutex.c.i

opt/pico/pico-sdk/src/common/pico_sync/mutex.s: opt/pico/pico-sdk/src/common/pico_sync/mutex.c.s
.PHONY : opt/pico/pico-sdk/src/common/pico_sync/mutex.s

# target to generate assembly for a file
opt/pico/pico-sdk/src/common/pico_sync/mutex.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/opt/pico/pico-sdk/src/common/pico_sync/mutex.c.s
.PHONY : opt/pico/pico-sdk/src/common/pico_sync/mutex.c.s

opt/pico/pico-sdk/src/common/pico_sync/sem.obj: opt/pico/pico-sdk/src/common/pico_sync/sem.c.obj
.PHONY : opt/pico/pico-sdk/src/common/pico_sync/sem.obj

# target to build an object file
opt/pico/pico-sdk/src/common/pico_sync/sem.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/opt/pico/pico-sdk/src/common/pico_sync/sem.c.obj
.PHONY : opt/pico/pico-sdk/src/common/pico_sync/sem.c.obj

opt/pico/pico-sdk/src/common/pico_sync/sem.i: opt/pico/pico-sdk/src/common/pico_sync/sem.c.i
.PHONY : opt/pico/pico-sdk/src/common/pico_sync/sem.i

# target to preprocess a source file
opt/pico/pico-sdk/src/common/pico_sync/sem.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/opt/pico/pico-sdk/src/common/pico_sync/sem.c.i
.PHONY : opt/pico/pico-sdk/src/common/pico_sync/sem.c.i

opt/pico/pico-sdk/src/common/pico_sync/sem.s: opt/pico/pico-sdk/src/common/pico_sync/sem.c.s
.PHONY : opt/pico/pico-sdk/src/common/pico_sync/sem.s

# target to generate assembly for a file
opt/pico/pico-sdk/src/common/pico_sync/sem.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/opt/pico/pico-sdk/src/common/pico_sync/sem.c.s
.PHONY : opt/pico/pico-sdk/src/common/pico_sync/sem.c.s

opt/pico/pico-sdk/src/common/pico_time/time.obj: opt/pico/pico-sdk/src/common/pico_time/time.c.obj
.PHONY : opt/pico/pico-sdk/src/common/pico_time/time.obj

# target to build an object file
opt/pico/pico-sdk/src/common/pico_time/time.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/opt/pico/pico-sdk/src/common/pico_time/time.c.obj
.PHONY : opt/pico/pico-sdk/src/common/pico_time/time.c.obj

opt/pico/pico-sdk/src/common/pico_time/time.i: opt/pico/pico-sdk/src/common/pico_time/time.c.i
.PHONY : opt/pico/pico-sdk/src/common/pico_time/time.i

# target to preprocess a source file
opt/pico/pico-sdk/src/common/pico_time/time.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/opt/pico/pico-sdk/src/common/pico_time/time.c.i
.PHONY : opt/pico/pico-sdk/src/common/pico_time/time.c.i

opt/pico/pico-sdk/src/common/pico_time/time.s: opt/pico/pico-sdk/src/common/pico_time/time.c.s
.PHONY : opt/pico/pico-sdk/src/common/pico_time/time.s

# target to generate assembly for a file
opt/pico/pico-sdk/src/common/pico_time/time.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/opt/pico/pico-sdk/src/common/pico_time/time.c.s
.PHONY : opt/pico/pico-sdk/src/common/pico_time/time.c.s

opt/pico/pico-sdk/src/common/pico_time/timeout_helper.obj: opt/pico/pico-sdk/src/common/pico_time/timeout_helper.c.obj
.PHONY : opt/pico/pico-sdk/src/common/pico_time/timeout_helper.obj

# target to build an object file
opt/pico/pico-sdk/src/common/pico_time/timeout_helper.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/opt/pico/pico-sdk/src/common/pico_time/timeout_helper.c.obj
.PHONY : opt/pico/pico-sdk/src/common/pico_time/timeout_helper.c.obj

opt/pico/pico-sdk/src/common/pico_time/timeout_helper.i: opt/pico/pico-sdk/src/common/pico_time/timeout_helper.c.i
.PHONY : opt/pico/pico-sdk/src/common/pico_time/timeout_helper.i

# target to preprocess a source file
opt/pico/pico-sdk/src/common/pico_time/timeout_helper.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/opt/pico/pico-sdk/src/common/pico_time/timeout_helper.c.i
.PHONY : opt/pico/pico-sdk/src/common/pico_time/timeout_helper.c.i

opt/pico/pico-sdk/src/common/pico_time/timeout_helper.s: opt/pico/pico-sdk/src/common/pico_time/timeout_helper.c.s
.PHONY : opt/pico/pico-sdk/src/common/pico_time/timeout_helper.s

# target to generate assembly for a file
opt/pico/pico-sdk/src/common/pico_time/timeout_helper.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/opt/pico/pico-sdk/src/common/pico_time/timeout_helper.c.s
.PHONY : opt/pico/pico-sdk/src/common/pico_time/timeout_helper.c.s

opt/pico/pico-sdk/src/common/pico_util/datetime.obj: opt/pico/pico-sdk/src/common/pico_util/datetime.c.obj
.PHONY : opt/pico/pico-sdk/src/common/pico_util/datetime.obj

# target to build an object file
opt/pico/pico-sdk/src/common/pico_util/datetime.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/opt/pico/pico-sdk/src/common/pico_util/datetime.c.obj
.PHONY : opt/pico/pico-sdk/src/common/pico_util/datetime.c.obj

opt/pico/pico-sdk/src/common/pico_util/datetime.i: opt/pico/pico-sdk/src/common/pico_util/datetime.c.i
.PHONY : opt/pico/pico-sdk/src/common/pico_util/datetime.i

# target to preprocess a source file
opt/pico/pico-sdk/src/common/pico_util/datetime.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/opt/pico/pico-sdk/src/common/pico_util/datetime.c.i
.PHONY : opt/pico/pico-sdk/src/common/pico_util/datetime.c.i

opt/pico/pico-sdk/src/common/pico_util/datetime.s: opt/pico/pico-sdk/src/common/pico_util/datetime.c.s
.PHONY : opt/pico/pico-sdk/src/common/pico_util/datetime.s

# target to generate assembly for a file
opt/pico/pico-sdk/src/common/pico_util/datetime.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/opt/pico/pico-sdk/src/common/pico_util/datetime.c.s
.PHONY : opt/pico/pico-sdk/src/common/pico_util/datetime.c.s

opt/pico/pico-sdk/src/common/pico_util/pheap.obj: opt/pico/pico-sdk/src/common/pico_util/pheap.c.obj
.PHONY : opt/pico/pico-sdk/src/common/pico_util/pheap.obj

# target to build an object file
opt/pico/pico-sdk/src/common/pico_util/pheap.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/opt/pico/pico-sdk/src/common/pico_util/pheap.c.obj
.PHONY : opt/pico/pico-sdk/src/common/pico_util/pheap.c.obj

opt/pico/pico-sdk/src/common/pico_util/pheap.i: opt/pico/pico-sdk/src/common/pico_util/pheap.c.i
.PHONY : opt/pico/pico-sdk/src/common/pico_util/pheap.i

# target to preprocess a source file
opt/pico/pico-sdk/src/common/pico_util/pheap.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/opt/pico/pico-sdk/src/common/pico_util/pheap.c.i
.PHONY : opt/pico/pico-sdk/src/common/pico_util/pheap.c.i

opt/pico/pico-sdk/src/common/pico_util/pheap.s: opt/pico/pico-sdk/src/common/pico_util/pheap.c.s
.PHONY : opt/pico/pico-sdk/src/common/pico_util/pheap.s

# target to generate assembly for a file
opt/pico/pico-sdk/src/common/pico_util/pheap.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/opt/pico/pico-sdk/src/common/pico_util/pheap.c.s
.PHONY : opt/pico/pico-sdk/src/common/pico_util/pheap.c.s

opt/pico/pico-sdk/src/common/pico_util/queue.obj: opt/pico/pico-sdk/src/common/pico_util/queue.c.obj
.PHONY : opt/pico/pico-sdk/src/common/pico_util/queue.obj

# target to build an object file
opt/pico/pico-sdk/src/common/pico_util/queue.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/opt/pico/pico-sdk/src/common/pico_util/queue.c.obj
.PHONY : opt/pico/pico-sdk/src/common/pico_util/queue.c.obj

opt/pico/pico-sdk/src/common/pico_util/queue.i: opt/pico/pico-sdk/src/common/pico_util/queue.c.i
.PHONY : opt/pico/pico-sdk/src/common/pico_util/queue.i

# target to preprocess a source file
opt/pico/pico-sdk/src/common/pico_util/queue.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/opt/pico/pico-sdk/src/common/pico_util/queue.c.i
.PHONY : opt/pico/pico-sdk/src/common/pico_util/queue.c.i

opt/pico/pico-sdk/src/common/pico_util/queue.s: opt/pico/pico-sdk/src/common/pico_util/queue.c.s
.PHONY : opt/pico/pico-sdk/src/common/pico_util/queue.s

# target to generate assembly for a file
opt/pico/pico-sdk/src/common/pico_util/queue.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/opt/pico/pico-sdk/src/common/pico_util/queue.c.s
.PHONY : opt/pico/pico-sdk/src/common/pico_util/queue.c.s

opt/pico/pico-sdk/src/rp2_common/hardware_adc/adc.obj: opt/pico/pico-sdk/src/rp2_common/hardware_adc/adc.c.obj
.PHONY : opt/pico/pico-sdk/src/rp2_common/hardware_adc/adc.obj

# target to build an object file
opt/pico/pico-sdk/src/rp2_common/hardware_adc/adc.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/opt/pico/pico-sdk/src/rp2_common/hardware_adc/adc.c.obj
.PHONY : opt/pico/pico-sdk/src/rp2_common/hardware_adc/adc.c.obj

opt/pico/pico-sdk/src/rp2_common/hardware_adc/adc.i: opt/pico/pico-sdk/src/rp2_common/hardware_adc/adc.c.i
.PHONY : opt/pico/pico-sdk/src/rp2_common/hardware_adc/adc.i

# target to preprocess a source file
opt/pico/pico-sdk/src/rp2_common/hardware_adc/adc.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/opt/pico/pico-sdk/src/rp2_common/hardware_adc/adc.c.i
.PHONY : opt/pico/pico-sdk/src/rp2_common/hardware_adc/adc.c.i

opt/pico/pico-sdk/src/rp2_common/hardware_adc/adc.s: opt/pico/pico-sdk/src/rp2_common/hardware_adc/adc.c.s
.PHONY : opt/pico/pico-sdk/src/rp2_common/hardware_adc/adc.s

# target to generate assembly for a file
opt/pico/pico-sdk/src/rp2_common/hardware_adc/adc.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/opt/pico/pico-sdk/src/rp2_common/hardware_adc/adc.c.s
.PHONY : opt/pico/pico-sdk/src/rp2_common/hardware_adc/adc.c.s

opt/pico/pico-sdk/src/rp2_common/hardware_claim/claim.obj: opt/pico/pico-sdk/src/rp2_common/hardware_claim/claim.c.obj
.PHONY : opt/pico/pico-sdk/src/rp2_common/hardware_claim/claim.obj

# target to build an object file
opt/pico/pico-sdk/src/rp2_common/hardware_claim/claim.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/opt/pico/pico-sdk/src/rp2_common/hardware_claim/claim.c.obj
.PHONY : opt/pico/pico-sdk/src/rp2_common/hardware_claim/claim.c.obj

opt/pico/pico-sdk/src/rp2_common/hardware_claim/claim.i: opt/pico/pico-sdk/src/rp2_common/hardware_claim/claim.c.i
.PHONY : opt/pico/pico-sdk/src/rp2_common/hardware_claim/claim.i

# target to preprocess a source file
opt/pico/pico-sdk/src/rp2_common/hardware_claim/claim.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/opt/pico/pico-sdk/src/rp2_common/hardware_claim/claim.c.i
.PHONY : opt/pico/pico-sdk/src/rp2_common/hardware_claim/claim.c.i

opt/pico/pico-sdk/src/rp2_common/hardware_claim/claim.s: opt/pico/pico-sdk/src/rp2_common/hardware_claim/claim.c.s
.PHONY : opt/pico/pico-sdk/src/rp2_common/hardware_claim/claim.s

# target to generate assembly for a file
opt/pico/pico-sdk/src/rp2_common/hardware_claim/claim.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/opt/pico/pico-sdk/src/rp2_common/hardware_claim/claim.c.s
.PHONY : opt/pico/pico-sdk/src/rp2_common/hardware_claim/claim.c.s

opt/pico/pico-sdk/src/rp2_common/hardware_clocks/clocks.obj: opt/pico/pico-sdk/src/rp2_common/hardware_clocks/clocks.c.obj
.PHONY : opt/pico/pico-sdk/src/rp2_common/hardware_clocks/clocks.obj

# target to build an object file
opt/pico/pico-sdk/src/rp2_common/hardware_clocks/clocks.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/opt/pico/pico-sdk/src/rp2_common/hardware_clocks/clocks.c.obj
.PHONY : opt/pico/pico-sdk/src/rp2_common/hardware_clocks/clocks.c.obj

opt/pico/pico-sdk/src/rp2_common/hardware_clocks/clocks.i: opt/pico/pico-sdk/src/rp2_common/hardware_clocks/clocks.c.i
.PHONY : opt/pico/pico-sdk/src/rp2_common/hardware_clocks/clocks.i

# target to preprocess a source file
opt/pico/pico-sdk/src/rp2_common/hardware_clocks/clocks.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/opt/pico/pico-sdk/src/rp2_common/hardware_clocks/clocks.c.i
.PHONY : opt/pico/pico-sdk/src/rp2_common/hardware_clocks/clocks.c.i

opt/pico/pico-sdk/src/rp2_common/hardware_clocks/clocks.s: opt/pico/pico-sdk/src/rp2_common/hardware_clocks/clocks.c.s
.PHONY : opt/pico/pico-sdk/src/rp2_common/hardware_clocks/clocks.s

# target to generate assembly for a file
opt/pico/pico-sdk/src/rp2_common/hardware_clocks/clocks.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/opt/pico/pico-sdk/src/rp2_common/hardware_clocks/clocks.c.s
.PHONY : opt/pico/pico-sdk/src/rp2_common/hardware_clocks/clocks.c.s

opt/pico/pico-sdk/src/rp2_common/hardware_divider/divider.obj: opt/pico/pico-sdk/src/rp2_common/hardware_divider/divider.S.obj
.PHONY : opt/pico/pico-sdk/src/rp2_common/hardware_divider/divider.obj

# target to build an object file
opt/pico/pico-sdk/src/rp2_common/hardware_divider/divider.S.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/opt/pico/pico-sdk/src/rp2_common/hardware_divider/divider.S.obj
.PHONY : opt/pico/pico-sdk/src/rp2_common/hardware_divider/divider.S.obj

opt/pico/pico-sdk/src/rp2_common/hardware_exception/exception.obj: opt/pico/pico-sdk/src/rp2_common/hardware_exception/exception.c.obj
.PHONY : opt/pico/pico-sdk/src/rp2_common/hardware_exception/exception.obj

# target to build an object file
opt/pico/pico-sdk/src/rp2_common/hardware_exception/exception.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/opt/pico/pico-sdk/src/rp2_common/hardware_exception/exception.c.obj
.PHONY : opt/pico/pico-sdk/src/rp2_common/hardware_exception/exception.c.obj

opt/pico/pico-sdk/src/rp2_common/hardware_exception/exception.i: opt/pico/pico-sdk/src/rp2_common/hardware_exception/exception.c.i
.PHONY : opt/pico/pico-sdk/src/rp2_common/hardware_exception/exception.i

# target to preprocess a source file
opt/pico/pico-sdk/src/rp2_common/hardware_exception/exception.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/opt/pico/pico-sdk/src/rp2_common/hardware_exception/exception.c.i
.PHONY : opt/pico/pico-sdk/src/rp2_common/hardware_exception/exception.c.i

opt/pico/pico-sdk/src/rp2_common/hardware_exception/exception.s: opt/pico/pico-sdk/src/rp2_common/hardware_exception/exception.c.s
.PHONY : opt/pico/pico-sdk/src/rp2_common/hardware_exception/exception.s

# target to generate assembly for a file
opt/pico/pico-sdk/src/rp2_common/hardware_exception/exception.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/opt/pico/pico-sdk/src/rp2_common/hardware_exception/exception.c.s
.PHONY : opt/pico/pico-sdk/src/rp2_common/hardware_exception/exception.c.s

opt/pico/pico-sdk/src/rp2_common/hardware_gpio/gpio.obj: opt/pico/pico-sdk/src/rp2_common/hardware_gpio/gpio.c.obj
.PHONY : opt/pico/pico-sdk/src/rp2_common/hardware_gpio/gpio.obj

# target to build an object file
opt/pico/pico-sdk/src/rp2_common/hardware_gpio/gpio.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/opt/pico/pico-sdk/src/rp2_common/hardware_gpio/gpio.c.obj
.PHONY : opt/pico/pico-sdk/src/rp2_common/hardware_gpio/gpio.c.obj

opt/pico/pico-sdk/src/rp2_common/hardware_gpio/gpio.i: opt/pico/pico-sdk/src/rp2_common/hardware_gpio/gpio.c.i
.PHONY : opt/pico/pico-sdk/src/rp2_common/hardware_gpio/gpio.i

# target to preprocess a source file
opt/pico/pico-sdk/src/rp2_common/hardware_gpio/gpio.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/opt/pico/pico-sdk/src/rp2_common/hardware_gpio/gpio.c.i
.PHONY : opt/pico/pico-sdk/src/rp2_common/hardware_gpio/gpio.c.i

opt/pico/pico-sdk/src/rp2_common/hardware_gpio/gpio.s: opt/pico/pico-sdk/src/rp2_common/hardware_gpio/gpio.c.s
.PHONY : opt/pico/pico-sdk/src/rp2_common/hardware_gpio/gpio.s

# target to generate assembly for a file
opt/pico/pico-sdk/src/rp2_common/hardware_gpio/gpio.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/opt/pico/pico-sdk/src/rp2_common/hardware_gpio/gpio.c.s
.PHONY : opt/pico/pico-sdk/src/rp2_common/hardware_gpio/gpio.c.s

opt/pico/pico-sdk/src/rp2_common/hardware_irq/irq.obj: opt/pico/pico-sdk/src/rp2_common/hardware_irq/irq.c.obj
.PHONY : opt/pico/pico-sdk/src/rp2_common/hardware_irq/irq.obj

# target to build an object file
opt/pico/pico-sdk/src/rp2_common/hardware_irq/irq.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/opt/pico/pico-sdk/src/rp2_common/hardware_irq/irq.c.obj
.PHONY : opt/pico/pico-sdk/src/rp2_common/hardware_irq/irq.c.obj

opt/pico/pico-sdk/src/rp2_common/hardware_irq/irq.i: opt/pico/pico-sdk/src/rp2_common/hardware_irq/irq.c.i
.PHONY : opt/pico/pico-sdk/src/rp2_common/hardware_irq/irq.i

# target to preprocess a source file
opt/pico/pico-sdk/src/rp2_common/hardware_irq/irq.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/opt/pico/pico-sdk/src/rp2_common/hardware_irq/irq.c.i
.PHONY : opt/pico/pico-sdk/src/rp2_common/hardware_irq/irq.c.i

opt/pico/pico-sdk/src/rp2_common/hardware_irq/irq.s: opt/pico/pico-sdk/src/rp2_common/hardware_irq/irq.c.s
.PHONY : opt/pico/pico-sdk/src/rp2_common/hardware_irq/irq.s

# target to generate assembly for a file
opt/pico/pico-sdk/src/rp2_common/hardware_irq/irq.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/opt/pico/pico-sdk/src/rp2_common/hardware_irq/irq.c.s
.PHONY : opt/pico/pico-sdk/src/rp2_common/hardware_irq/irq.c.s

opt/pico/pico-sdk/src/rp2_common/hardware_irq/irq_handler_chain.obj: opt/pico/pico-sdk/src/rp2_common/hardware_irq/irq_handler_chain.S.obj
.PHONY : opt/pico/pico-sdk/src/rp2_common/hardware_irq/irq_handler_chain.obj

# target to build an object file
opt/pico/pico-sdk/src/rp2_common/hardware_irq/irq_handler_chain.S.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/opt/pico/pico-sdk/src/rp2_common/hardware_irq/irq_handler_chain.S.obj
.PHONY : opt/pico/pico-sdk/src/rp2_common/hardware_irq/irq_handler_chain.S.obj

opt/pico/pico-sdk/src/rp2_common/hardware_pll/pll.obj: opt/pico/pico-sdk/src/rp2_common/hardware_pll/pll.c.obj
.PHONY : opt/pico/pico-sdk/src/rp2_common/hardware_pll/pll.obj

# target to build an object file
opt/pico/pico-sdk/src/rp2_common/hardware_pll/pll.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/opt/pico/pico-sdk/src/rp2_common/hardware_pll/pll.c.obj
.PHONY : opt/pico/pico-sdk/src/rp2_common/hardware_pll/pll.c.obj

opt/pico/pico-sdk/src/rp2_common/hardware_pll/pll.i: opt/pico/pico-sdk/src/rp2_common/hardware_pll/pll.c.i
.PHONY : opt/pico/pico-sdk/src/rp2_common/hardware_pll/pll.i

# target to preprocess a source file
opt/pico/pico-sdk/src/rp2_common/hardware_pll/pll.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/opt/pico/pico-sdk/src/rp2_common/hardware_pll/pll.c.i
.PHONY : opt/pico/pico-sdk/src/rp2_common/hardware_pll/pll.c.i

opt/pico/pico-sdk/src/rp2_common/hardware_pll/pll.s: opt/pico/pico-sdk/src/rp2_common/hardware_pll/pll.c.s
.PHONY : opt/pico/pico-sdk/src/rp2_common/hardware_pll/pll.s

# target to generate assembly for a file
opt/pico/pico-sdk/src/rp2_common/hardware_pll/pll.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/opt/pico/pico-sdk/src/rp2_common/hardware_pll/pll.c.s
.PHONY : opt/pico/pico-sdk/src/rp2_common/hardware_pll/pll.c.s

opt/pico/pico-sdk/src/rp2_common/hardware_sync/sync.obj: opt/pico/pico-sdk/src/rp2_common/hardware_sync/sync.c.obj
.PHONY : opt/pico/pico-sdk/src/rp2_common/hardware_sync/sync.obj

# target to build an object file
opt/pico/pico-sdk/src/rp2_common/hardware_sync/sync.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/opt/pico/pico-sdk/src/rp2_common/hardware_sync/sync.c.obj
.PHONY : opt/pico/pico-sdk/src/rp2_common/hardware_sync/sync.c.obj

opt/pico/pico-sdk/src/rp2_common/hardware_sync/sync.i: opt/pico/pico-sdk/src/rp2_common/hardware_sync/sync.c.i
.PHONY : opt/pico/pico-sdk/src/rp2_common/hardware_sync/sync.i

# target to preprocess a source file
opt/pico/pico-sdk/src/rp2_common/hardware_sync/sync.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/opt/pico/pico-sdk/src/rp2_common/hardware_sync/sync.c.i
.PHONY : opt/pico/pico-sdk/src/rp2_common/hardware_sync/sync.c.i

opt/pico/pico-sdk/src/rp2_common/hardware_sync/sync.s: opt/pico/pico-sdk/src/rp2_common/hardware_sync/sync.c.s
.PHONY : opt/pico/pico-sdk/src/rp2_common/hardware_sync/sync.s

# target to generate assembly for a file
opt/pico/pico-sdk/src/rp2_common/hardware_sync/sync.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/opt/pico/pico-sdk/src/rp2_common/hardware_sync/sync.c.s
.PHONY : opt/pico/pico-sdk/src/rp2_common/hardware_sync/sync.c.s

opt/pico/pico-sdk/src/rp2_common/hardware_timer/timer.obj: opt/pico/pico-sdk/src/rp2_common/hardware_timer/timer.c.obj
.PHONY : opt/pico/pico-sdk/src/rp2_common/hardware_timer/timer.obj

# target to build an object file
opt/pico/pico-sdk/src/rp2_common/hardware_timer/timer.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/opt/pico/pico-sdk/src/rp2_common/hardware_timer/timer.c.obj
.PHONY : opt/pico/pico-sdk/src/rp2_common/hardware_timer/timer.c.obj

opt/pico/pico-sdk/src/rp2_common/hardware_timer/timer.i: opt/pico/pico-sdk/src/rp2_common/hardware_timer/timer.c.i
.PHONY : opt/pico/pico-sdk/src/rp2_common/hardware_timer/timer.i

# target to preprocess a source file
opt/pico/pico-sdk/src/rp2_common/hardware_timer/timer.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/opt/pico/pico-sdk/src/rp2_common/hardware_timer/timer.c.i
.PHONY : opt/pico/pico-sdk/src/rp2_common/hardware_timer/timer.c.i

opt/pico/pico-sdk/src/rp2_common/hardware_timer/timer.s: opt/pico/pico-sdk/src/rp2_common/hardware_timer/timer.c.s
.PHONY : opt/pico/pico-sdk/src/rp2_common/hardware_timer/timer.s

# target to generate assembly for a file
opt/pico/pico-sdk/src/rp2_common/hardware_timer/timer.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/opt/pico/pico-sdk/src/rp2_common/hardware_timer/timer.c.s
.PHONY : opt/pico/pico-sdk/src/rp2_common/hardware_timer/timer.c.s

opt/pico/pico-sdk/src/rp2_common/hardware_uart/uart.obj: opt/pico/pico-sdk/src/rp2_common/hardware_uart/uart.c.obj
.PHONY : opt/pico/pico-sdk/src/rp2_common/hardware_uart/uart.obj

# target to build an object file
opt/pico/pico-sdk/src/rp2_common/hardware_uart/uart.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/opt/pico/pico-sdk/src/rp2_common/hardware_uart/uart.c.obj
.PHONY : opt/pico/pico-sdk/src/rp2_common/hardware_uart/uart.c.obj

opt/pico/pico-sdk/src/rp2_common/hardware_uart/uart.i: opt/pico/pico-sdk/src/rp2_common/hardware_uart/uart.c.i
.PHONY : opt/pico/pico-sdk/src/rp2_common/hardware_uart/uart.i

# target to preprocess a source file
opt/pico/pico-sdk/src/rp2_common/hardware_uart/uart.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/opt/pico/pico-sdk/src/rp2_common/hardware_uart/uart.c.i
.PHONY : opt/pico/pico-sdk/src/rp2_common/hardware_uart/uart.c.i

opt/pico/pico-sdk/src/rp2_common/hardware_uart/uart.s: opt/pico/pico-sdk/src/rp2_common/hardware_uart/uart.c.s
.PHONY : opt/pico/pico-sdk/src/rp2_common/hardware_uart/uart.s

# target to generate assembly for a file
opt/pico/pico-sdk/src/rp2_common/hardware_uart/uart.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/opt/pico/pico-sdk/src/rp2_common/hardware_uart/uart.c.s
.PHONY : opt/pico/pico-sdk/src/rp2_common/hardware_uart/uart.c.s

opt/pico/pico-sdk/src/rp2_common/hardware_vreg/vreg.obj: opt/pico/pico-sdk/src/rp2_common/hardware_vreg/vreg.c.obj
.PHONY : opt/pico/pico-sdk/src/rp2_common/hardware_vreg/vreg.obj

# target to build an object file
opt/pico/pico-sdk/src/rp2_common/hardware_vreg/vreg.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/opt/pico/pico-sdk/src/rp2_common/hardware_vreg/vreg.c.obj
.PHONY : opt/pico/pico-sdk/src/rp2_common/hardware_vreg/vreg.c.obj

opt/pico/pico-sdk/src/rp2_common/hardware_vreg/vreg.i: opt/pico/pico-sdk/src/rp2_common/hardware_vreg/vreg.c.i
.PHONY : opt/pico/pico-sdk/src/rp2_common/hardware_vreg/vreg.i

# target to preprocess a source file
opt/pico/pico-sdk/src/rp2_common/hardware_vreg/vreg.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/opt/pico/pico-sdk/src/rp2_common/hardware_vreg/vreg.c.i
.PHONY : opt/pico/pico-sdk/src/rp2_common/hardware_vreg/vreg.c.i

opt/pico/pico-sdk/src/rp2_common/hardware_vreg/vreg.s: opt/pico/pico-sdk/src/rp2_common/hardware_vreg/vreg.c.s
.PHONY : opt/pico/pico-sdk/src/rp2_common/hardware_vreg/vreg.s

# target to generate assembly for a file
opt/pico/pico-sdk/src/rp2_common/hardware_vreg/vreg.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/opt/pico/pico-sdk/src/rp2_common/hardware_vreg/vreg.c.s
.PHONY : opt/pico/pico-sdk/src/rp2_common/hardware_vreg/vreg.c.s

opt/pico/pico-sdk/src/rp2_common/hardware_watchdog/watchdog.obj: opt/pico/pico-sdk/src/rp2_common/hardware_watchdog/watchdog.c.obj
.PHONY : opt/pico/pico-sdk/src/rp2_common/hardware_watchdog/watchdog.obj

# target to build an object file
opt/pico/pico-sdk/src/rp2_common/hardware_watchdog/watchdog.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/opt/pico/pico-sdk/src/rp2_common/hardware_watchdog/watchdog.c.obj
.PHONY : opt/pico/pico-sdk/src/rp2_common/hardware_watchdog/watchdog.c.obj

opt/pico/pico-sdk/src/rp2_common/hardware_watchdog/watchdog.i: opt/pico/pico-sdk/src/rp2_common/hardware_watchdog/watchdog.c.i
.PHONY : opt/pico/pico-sdk/src/rp2_common/hardware_watchdog/watchdog.i

# target to preprocess a source file
opt/pico/pico-sdk/src/rp2_common/hardware_watchdog/watchdog.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/opt/pico/pico-sdk/src/rp2_common/hardware_watchdog/watchdog.c.i
.PHONY : opt/pico/pico-sdk/src/rp2_common/hardware_watchdog/watchdog.c.i

opt/pico/pico-sdk/src/rp2_common/hardware_watchdog/watchdog.s: opt/pico/pico-sdk/src/rp2_common/hardware_watchdog/watchdog.c.s
.PHONY : opt/pico/pico-sdk/src/rp2_common/hardware_watchdog/watchdog.s

# target to generate assembly for a file
opt/pico/pico-sdk/src/rp2_common/hardware_watchdog/watchdog.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/opt/pico/pico-sdk/src/rp2_common/hardware_watchdog/watchdog.c.s
.PHONY : opt/pico/pico-sdk/src/rp2_common/hardware_watchdog/watchdog.c.s

opt/pico/pico-sdk/src/rp2_common/hardware_xosc/xosc.obj: opt/pico/pico-sdk/src/rp2_common/hardware_xosc/xosc.c.obj
.PHONY : opt/pico/pico-sdk/src/rp2_common/hardware_xosc/xosc.obj

# target to build an object file
opt/pico/pico-sdk/src/rp2_common/hardware_xosc/xosc.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/opt/pico/pico-sdk/src/rp2_common/hardware_xosc/xosc.c.obj
.PHONY : opt/pico/pico-sdk/src/rp2_common/hardware_xosc/xosc.c.obj

opt/pico/pico-sdk/src/rp2_common/hardware_xosc/xosc.i: opt/pico/pico-sdk/src/rp2_common/hardware_xosc/xosc.c.i
.PHONY : opt/pico/pico-sdk/src/rp2_common/hardware_xosc/xosc.i

# target to preprocess a source file
opt/pico/pico-sdk/src/rp2_common/hardware_xosc/xosc.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/opt/pico/pico-sdk/src/rp2_common/hardware_xosc/xosc.c.i
.PHONY : opt/pico/pico-sdk/src/rp2_common/hardware_xosc/xosc.c.i

opt/pico/pico-sdk/src/rp2_common/hardware_xosc/xosc.s: opt/pico/pico-sdk/src/rp2_common/hardware_xosc/xosc.c.s
.PHONY : opt/pico/pico-sdk/src/rp2_common/hardware_xosc/xosc.s

# target to generate assembly for a file
opt/pico/pico-sdk/src/rp2_common/hardware_xosc/xosc.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/opt/pico/pico-sdk/src/rp2_common/hardware_xosc/xosc.c.s
.PHONY : opt/pico/pico-sdk/src/rp2_common/hardware_xosc/xosc.c.s

opt/pico/pico-sdk/src/rp2_common/pico_bit_ops/bit_ops_aeabi.obj: opt/pico/pico-sdk/src/rp2_common/pico_bit_ops/bit_ops_aeabi.S.obj
.PHONY : opt/pico/pico-sdk/src/rp2_common/pico_bit_ops/bit_ops_aeabi.obj

# target to build an object file
opt/pico/pico-sdk/src/rp2_common/pico_bit_ops/bit_ops_aeabi.S.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/opt/pico/pico-sdk/src/rp2_common/pico_bit_ops/bit_ops_aeabi.S.obj
.PHONY : opt/pico/pico-sdk/src/rp2_common/pico_bit_ops/bit_ops_aeabi.S.obj

opt/pico/pico-sdk/src/rp2_common/pico_bootrom/bootrom.obj: opt/pico/pico-sdk/src/rp2_common/pico_bootrom/bootrom.c.obj
.PHONY : opt/pico/pico-sdk/src/rp2_common/pico_bootrom/bootrom.obj

# target to build an object file
opt/pico/pico-sdk/src/rp2_common/pico_bootrom/bootrom.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/opt/pico/pico-sdk/src/rp2_common/pico_bootrom/bootrom.c.obj
.PHONY : opt/pico/pico-sdk/src/rp2_common/pico_bootrom/bootrom.c.obj

opt/pico/pico-sdk/src/rp2_common/pico_bootrom/bootrom.i: opt/pico/pico-sdk/src/rp2_common/pico_bootrom/bootrom.c.i
.PHONY : opt/pico/pico-sdk/src/rp2_common/pico_bootrom/bootrom.i

# target to preprocess a source file
opt/pico/pico-sdk/src/rp2_common/pico_bootrom/bootrom.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/opt/pico/pico-sdk/src/rp2_common/pico_bootrom/bootrom.c.i
.PHONY : opt/pico/pico-sdk/src/rp2_common/pico_bootrom/bootrom.c.i

opt/pico/pico-sdk/src/rp2_common/pico_bootrom/bootrom.s: opt/pico/pico-sdk/src/rp2_common/pico_bootrom/bootrom.c.s
.PHONY : opt/pico/pico-sdk/src/rp2_common/pico_bootrom/bootrom.s

# target to generate assembly for a file
opt/pico/pico-sdk/src/rp2_common/pico_bootrom/bootrom.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/opt/pico/pico-sdk/src/rp2_common/pico_bootrom/bootrom.c.s
.PHONY : opt/pico/pico-sdk/src/rp2_common/pico_bootrom/bootrom.c.s

opt/pico/pico-sdk/src/rp2_common/pico_divider/divider.obj: opt/pico/pico-sdk/src/rp2_common/pico_divider/divider.S.obj
.PHONY : opt/pico/pico-sdk/src/rp2_common/pico_divider/divider.obj

# target to build an object file
opt/pico/pico-sdk/src/rp2_common/pico_divider/divider.S.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/opt/pico/pico-sdk/src/rp2_common/pico_divider/divider.S.obj
.PHONY : opt/pico/pico-sdk/src/rp2_common/pico_divider/divider.S.obj

opt/pico/pico-sdk/src/rp2_common/pico_double/double_aeabi.obj: opt/pico/pico-sdk/src/rp2_common/pico_double/double_aeabi.S.obj
.PHONY : opt/pico/pico-sdk/src/rp2_common/pico_double/double_aeabi.obj

# target to build an object file
opt/pico/pico-sdk/src/rp2_common/pico_double/double_aeabi.S.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/opt/pico/pico-sdk/src/rp2_common/pico_double/double_aeabi.S.obj
.PHONY : opt/pico/pico-sdk/src/rp2_common/pico_double/double_aeabi.S.obj

opt/pico/pico-sdk/src/rp2_common/pico_double/double_init_rom.obj: opt/pico/pico-sdk/src/rp2_common/pico_double/double_init_rom.c.obj
.PHONY : opt/pico/pico-sdk/src/rp2_common/pico_double/double_init_rom.obj

# target to build an object file
opt/pico/pico-sdk/src/rp2_common/pico_double/double_init_rom.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/opt/pico/pico-sdk/src/rp2_common/pico_double/double_init_rom.c.obj
.PHONY : opt/pico/pico-sdk/src/rp2_common/pico_double/double_init_rom.c.obj

opt/pico/pico-sdk/src/rp2_common/pico_double/double_init_rom.i: opt/pico/pico-sdk/src/rp2_common/pico_double/double_init_rom.c.i
.PHONY : opt/pico/pico-sdk/src/rp2_common/pico_double/double_init_rom.i

# target to preprocess a source file
opt/pico/pico-sdk/src/rp2_common/pico_double/double_init_rom.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/opt/pico/pico-sdk/src/rp2_common/pico_double/double_init_rom.c.i
.PHONY : opt/pico/pico-sdk/src/rp2_common/pico_double/double_init_rom.c.i

opt/pico/pico-sdk/src/rp2_common/pico_double/double_init_rom.s: opt/pico/pico-sdk/src/rp2_common/pico_double/double_init_rom.c.s
.PHONY : opt/pico/pico-sdk/src/rp2_common/pico_double/double_init_rom.s

# target to generate assembly for a file
opt/pico/pico-sdk/src/rp2_common/pico_double/double_init_rom.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/opt/pico/pico-sdk/src/rp2_common/pico_double/double_init_rom.c.s
.PHONY : opt/pico/pico-sdk/src/rp2_common/pico_double/double_init_rom.c.s

opt/pico/pico-sdk/src/rp2_common/pico_double/double_math.obj: opt/pico/pico-sdk/src/rp2_common/pico_double/double_math.c.obj
.PHONY : opt/pico/pico-sdk/src/rp2_common/pico_double/double_math.obj

# target to build an object file
opt/pico/pico-sdk/src/rp2_common/pico_double/double_math.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/opt/pico/pico-sdk/src/rp2_common/pico_double/double_math.c.obj
.PHONY : opt/pico/pico-sdk/src/rp2_common/pico_double/double_math.c.obj

opt/pico/pico-sdk/src/rp2_common/pico_double/double_math.i: opt/pico/pico-sdk/src/rp2_common/pico_double/double_math.c.i
.PHONY : opt/pico/pico-sdk/src/rp2_common/pico_double/double_math.i

# target to preprocess a source file
opt/pico/pico-sdk/src/rp2_common/pico_double/double_math.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/opt/pico/pico-sdk/src/rp2_common/pico_double/double_math.c.i
.PHONY : opt/pico/pico-sdk/src/rp2_common/pico_double/double_math.c.i

opt/pico/pico-sdk/src/rp2_common/pico_double/double_math.s: opt/pico/pico-sdk/src/rp2_common/pico_double/double_math.c.s
.PHONY : opt/pico/pico-sdk/src/rp2_common/pico_double/double_math.s

# target to generate assembly for a file
opt/pico/pico-sdk/src/rp2_common/pico_double/double_math.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/opt/pico/pico-sdk/src/rp2_common/pico_double/double_math.c.s
.PHONY : opt/pico/pico-sdk/src/rp2_common/pico_double/double_math.c.s

opt/pico/pico-sdk/src/rp2_common/pico_double/double_v1_rom_shim.obj: opt/pico/pico-sdk/src/rp2_common/pico_double/double_v1_rom_shim.S.obj
.PHONY : opt/pico/pico-sdk/src/rp2_common/pico_double/double_v1_rom_shim.obj

# target to build an object file
opt/pico/pico-sdk/src/rp2_common/pico_double/double_v1_rom_shim.S.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/opt/pico/pico-sdk/src/rp2_common/pico_double/double_v1_rom_shim.S.obj
.PHONY : opt/pico/pico-sdk/src/rp2_common/pico_double/double_v1_rom_shim.S.obj

opt/pico/pico-sdk/src/rp2_common/pico_float/float_aeabi.obj: opt/pico/pico-sdk/src/rp2_common/pico_float/float_aeabi.S.obj
.PHONY : opt/pico/pico-sdk/src/rp2_common/pico_float/float_aeabi.obj

# target to build an object file
opt/pico/pico-sdk/src/rp2_common/pico_float/float_aeabi.S.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/opt/pico/pico-sdk/src/rp2_common/pico_float/float_aeabi.S.obj
.PHONY : opt/pico/pico-sdk/src/rp2_common/pico_float/float_aeabi.S.obj

opt/pico/pico-sdk/src/rp2_common/pico_float/float_init_rom.obj: opt/pico/pico-sdk/src/rp2_common/pico_float/float_init_rom.c.obj
.PHONY : opt/pico/pico-sdk/src/rp2_common/pico_float/float_init_rom.obj

# target to build an object file
opt/pico/pico-sdk/src/rp2_common/pico_float/float_init_rom.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/opt/pico/pico-sdk/src/rp2_common/pico_float/float_init_rom.c.obj
.PHONY : opt/pico/pico-sdk/src/rp2_common/pico_float/float_init_rom.c.obj

opt/pico/pico-sdk/src/rp2_common/pico_float/float_init_rom.i: opt/pico/pico-sdk/src/rp2_common/pico_float/float_init_rom.c.i
.PHONY : opt/pico/pico-sdk/src/rp2_common/pico_float/float_init_rom.i

# target to preprocess a source file
opt/pico/pico-sdk/src/rp2_common/pico_float/float_init_rom.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/opt/pico/pico-sdk/src/rp2_common/pico_float/float_init_rom.c.i
.PHONY : opt/pico/pico-sdk/src/rp2_common/pico_float/float_init_rom.c.i

opt/pico/pico-sdk/src/rp2_common/pico_float/float_init_rom.s: opt/pico/pico-sdk/src/rp2_common/pico_float/float_init_rom.c.s
.PHONY : opt/pico/pico-sdk/src/rp2_common/pico_float/float_init_rom.s

# target to generate assembly for a file
opt/pico/pico-sdk/src/rp2_common/pico_float/float_init_rom.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/opt/pico/pico-sdk/src/rp2_common/pico_float/float_init_rom.c.s
.PHONY : opt/pico/pico-sdk/src/rp2_common/pico_float/float_init_rom.c.s

opt/pico/pico-sdk/src/rp2_common/pico_float/float_math.obj: opt/pico/pico-sdk/src/rp2_common/pico_float/float_math.c.obj
.PHONY : opt/pico/pico-sdk/src/rp2_common/pico_float/float_math.obj

# target to build an object file
opt/pico/pico-sdk/src/rp2_common/pico_float/float_math.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/opt/pico/pico-sdk/src/rp2_common/pico_float/float_math.c.obj
.PHONY : opt/pico/pico-sdk/src/rp2_common/pico_float/float_math.c.obj

opt/pico/pico-sdk/src/rp2_common/pico_float/float_math.i: opt/pico/pico-sdk/src/rp2_common/pico_float/float_math.c.i
.PHONY : opt/pico/pico-sdk/src/rp2_common/pico_float/float_math.i

# target to preprocess a source file
opt/pico/pico-sdk/src/rp2_common/pico_float/float_math.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/opt/pico/pico-sdk/src/rp2_common/pico_float/float_math.c.i
.PHONY : opt/pico/pico-sdk/src/rp2_common/pico_float/float_math.c.i

opt/pico/pico-sdk/src/rp2_common/pico_float/float_math.s: opt/pico/pico-sdk/src/rp2_common/pico_float/float_math.c.s
.PHONY : opt/pico/pico-sdk/src/rp2_common/pico_float/float_math.s

# target to generate assembly for a file
opt/pico/pico-sdk/src/rp2_common/pico_float/float_math.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/opt/pico/pico-sdk/src/rp2_common/pico_float/float_math.c.s
.PHONY : opt/pico/pico-sdk/src/rp2_common/pico_float/float_math.c.s

opt/pico/pico-sdk/src/rp2_common/pico_float/float_v1_rom_shim.obj: opt/pico/pico-sdk/src/rp2_common/pico_float/float_v1_rom_shim.S.obj
.PHONY : opt/pico/pico-sdk/src/rp2_common/pico_float/float_v1_rom_shim.obj

# target to build an object file
opt/pico/pico-sdk/src/rp2_common/pico_float/float_v1_rom_shim.S.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/opt/pico/pico-sdk/src/rp2_common/pico_float/float_v1_rom_shim.S.obj
.PHONY : opt/pico/pico-sdk/src/rp2_common/pico_float/float_v1_rom_shim.S.obj

opt/pico/pico-sdk/src/rp2_common/pico_int64_ops/pico_int64_ops_aeabi.obj: opt/pico/pico-sdk/src/rp2_common/pico_int64_ops/pico_int64_ops_aeabi.S.obj
.PHONY : opt/pico/pico-sdk/src/rp2_common/pico_int64_ops/pico_int64_ops_aeabi.obj

# target to build an object file
opt/pico/pico-sdk/src/rp2_common/pico_int64_ops/pico_int64_ops_aeabi.S.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/opt/pico/pico-sdk/src/rp2_common/pico_int64_ops/pico_int64_ops_aeabi.S.obj
.PHONY : opt/pico/pico-sdk/src/rp2_common/pico_int64_ops/pico_int64_ops_aeabi.S.obj

opt/pico/pico-sdk/src/rp2_common/pico_malloc/pico_malloc.obj: opt/pico/pico-sdk/src/rp2_common/pico_malloc/pico_malloc.c.obj
.PHONY : opt/pico/pico-sdk/src/rp2_common/pico_malloc/pico_malloc.obj

# target to build an object file
opt/pico/pico-sdk/src/rp2_common/pico_malloc/pico_malloc.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/opt/pico/pico-sdk/src/rp2_common/pico_malloc/pico_malloc.c.obj
.PHONY : opt/pico/pico-sdk/src/rp2_common/pico_malloc/pico_malloc.c.obj

opt/pico/pico-sdk/src/rp2_common/pico_malloc/pico_malloc.i: opt/pico/pico-sdk/src/rp2_common/pico_malloc/pico_malloc.c.i
.PHONY : opt/pico/pico-sdk/src/rp2_common/pico_malloc/pico_malloc.i

# target to preprocess a source file
opt/pico/pico-sdk/src/rp2_common/pico_malloc/pico_malloc.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/opt/pico/pico-sdk/src/rp2_common/pico_malloc/pico_malloc.c.i
.PHONY : opt/pico/pico-sdk/src/rp2_common/pico_malloc/pico_malloc.c.i

opt/pico/pico-sdk/src/rp2_common/pico_malloc/pico_malloc.s: opt/pico/pico-sdk/src/rp2_common/pico_malloc/pico_malloc.c.s
.PHONY : opt/pico/pico-sdk/src/rp2_common/pico_malloc/pico_malloc.s

# target to generate assembly for a file
opt/pico/pico-sdk/src/rp2_common/pico_malloc/pico_malloc.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/opt/pico/pico-sdk/src/rp2_common/pico_malloc/pico_malloc.c.s
.PHONY : opt/pico/pico-sdk/src/rp2_common/pico_malloc/pico_malloc.c.s

opt/pico/pico-sdk/src/rp2_common/pico_mem_ops/mem_ops_aeabi.obj: opt/pico/pico-sdk/src/rp2_common/pico_mem_ops/mem_ops_aeabi.S.obj
.PHONY : opt/pico/pico-sdk/src/rp2_common/pico_mem_ops/mem_ops_aeabi.obj

# target to build an object file
opt/pico/pico-sdk/src/rp2_common/pico_mem_ops/mem_ops_aeabi.S.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/opt/pico/pico-sdk/src/rp2_common/pico_mem_ops/mem_ops_aeabi.S.obj
.PHONY : opt/pico/pico-sdk/src/rp2_common/pico_mem_ops/mem_ops_aeabi.S.obj

opt/pico/pico-sdk/src/rp2_common/pico_multicore/multicore.obj: opt/pico/pico-sdk/src/rp2_common/pico_multicore/multicore.c.obj
.PHONY : opt/pico/pico-sdk/src/rp2_common/pico_multicore/multicore.obj

# target to build an object file
opt/pico/pico-sdk/src/rp2_common/pico_multicore/multicore.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/opt/pico/pico-sdk/src/rp2_common/pico_multicore/multicore.c.obj
.PHONY : opt/pico/pico-sdk/src/rp2_common/pico_multicore/multicore.c.obj

opt/pico/pico-sdk/src/rp2_common/pico_multicore/multicore.i: opt/pico/pico-sdk/src/rp2_common/pico_multicore/multicore.c.i
.PHONY : opt/pico/pico-sdk/src/rp2_common/pico_multicore/multicore.i

# target to preprocess a source file
opt/pico/pico-sdk/src/rp2_common/pico_multicore/multicore.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/opt/pico/pico-sdk/src/rp2_common/pico_multicore/multicore.c.i
.PHONY : opt/pico/pico-sdk/src/rp2_common/pico_multicore/multicore.c.i

opt/pico/pico-sdk/src/rp2_common/pico_multicore/multicore.s: opt/pico/pico-sdk/src/rp2_common/pico_multicore/multicore.c.s
.PHONY : opt/pico/pico-sdk/src/rp2_common/pico_multicore/multicore.s

# target to generate assembly for a file
opt/pico/pico-sdk/src/rp2_common/pico_multicore/multicore.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/opt/pico/pico-sdk/src/rp2_common/pico_multicore/multicore.c.s
.PHONY : opt/pico/pico-sdk/src/rp2_common/pico_multicore/multicore.c.s

opt/pico/pico-sdk/src/rp2_common/pico_platform/platform.obj: opt/pico/pico-sdk/src/rp2_common/pico_platform/platform.c.obj
.PHONY : opt/pico/pico-sdk/src/rp2_common/pico_platform/platform.obj

# target to build an object file
opt/pico/pico-sdk/src/rp2_common/pico_platform/platform.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/opt/pico/pico-sdk/src/rp2_common/pico_platform/platform.c.obj
.PHONY : opt/pico/pico-sdk/src/rp2_common/pico_platform/platform.c.obj

opt/pico/pico-sdk/src/rp2_common/pico_platform/platform.i: opt/pico/pico-sdk/src/rp2_common/pico_platform/platform.c.i
.PHONY : opt/pico/pico-sdk/src/rp2_common/pico_platform/platform.i

# target to preprocess a source file
opt/pico/pico-sdk/src/rp2_common/pico_platform/platform.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/opt/pico/pico-sdk/src/rp2_common/pico_platform/platform.c.i
.PHONY : opt/pico/pico-sdk/src/rp2_common/pico_platform/platform.c.i

opt/pico/pico-sdk/src/rp2_common/pico_platform/platform.s: opt/pico/pico-sdk/src/rp2_common/pico_platform/platform.c.s
.PHONY : opt/pico/pico-sdk/src/rp2_common/pico_platform/platform.s

# target to generate assembly for a file
opt/pico/pico-sdk/src/rp2_common/pico_platform/platform.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/opt/pico/pico-sdk/src/rp2_common/pico_platform/platform.c.s
.PHONY : opt/pico/pico-sdk/src/rp2_common/pico_platform/platform.c.s

opt/pico/pico-sdk/src/rp2_common/pico_printf/printf.obj: opt/pico/pico-sdk/src/rp2_common/pico_printf/printf.c.obj
.PHONY : opt/pico/pico-sdk/src/rp2_common/pico_printf/printf.obj

# target to build an object file
opt/pico/pico-sdk/src/rp2_common/pico_printf/printf.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/opt/pico/pico-sdk/src/rp2_common/pico_printf/printf.c.obj
.PHONY : opt/pico/pico-sdk/src/rp2_common/pico_printf/printf.c.obj

opt/pico/pico-sdk/src/rp2_common/pico_printf/printf.i: opt/pico/pico-sdk/src/rp2_common/pico_printf/printf.c.i
.PHONY : opt/pico/pico-sdk/src/rp2_common/pico_printf/printf.i

# target to preprocess a source file
opt/pico/pico-sdk/src/rp2_common/pico_printf/printf.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/opt/pico/pico-sdk/src/rp2_common/pico_printf/printf.c.i
.PHONY : opt/pico/pico-sdk/src/rp2_common/pico_printf/printf.c.i

opt/pico/pico-sdk/src/rp2_common/pico_printf/printf.s: opt/pico/pico-sdk/src/rp2_common/pico_printf/printf.c.s
.PHONY : opt/pico/pico-sdk/src/rp2_common/pico_printf/printf.s

# target to generate assembly for a file
opt/pico/pico-sdk/src/rp2_common/pico_printf/printf.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/opt/pico/pico-sdk/src/rp2_common/pico_printf/printf.c.s
.PHONY : opt/pico/pico-sdk/src/rp2_common/pico_printf/printf.c.s

opt/pico/pico-sdk/src/rp2_common/pico_runtime/runtime.obj: opt/pico/pico-sdk/src/rp2_common/pico_runtime/runtime.c.obj
.PHONY : opt/pico/pico-sdk/src/rp2_common/pico_runtime/runtime.obj

# target to build an object file
opt/pico/pico-sdk/src/rp2_common/pico_runtime/runtime.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/opt/pico/pico-sdk/src/rp2_common/pico_runtime/runtime.c.obj
.PHONY : opt/pico/pico-sdk/src/rp2_common/pico_runtime/runtime.c.obj

opt/pico/pico-sdk/src/rp2_common/pico_runtime/runtime.i: opt/pico/pico-sdk/src/rp2_common/pico_runtime/runtime.c.i
.PHONY : opt/pico/pico-sdk/src/rp2_common/pico_runtime/runtime.i

# target to preprocess a source file
opt/pico/pico-sdk/src/rp2_common/pico_runtime/runtime.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/opt/pico/pico-sdk/src/rp2_common/pico_runtime/runtime.c.i
.PHONY : opt/pico/pico-sdk/src/rp2_common/pico_runtime/runtime.c.i

opt/pico/pico-sdk/src/rp2_common/pico_runtime/runtime.s: opt/pico/pico-sdk/src/rp2_common/pico_runtime/runtime.c.s
.PHONY : opt/pico/pico-sdk/src/rp2_common/pico_runtime/runtime.s

# target to generate assembly for a file
opt/pico/pico-sdk/src/rp2_common/pico_runtime/runtime.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/opt/pico/pico-sdk/src/rp2_common/pico_runtime/runtime.c.s
.PHONY : opt/pico/pico-sdk/src/rp2_common/pico_runtime/runtime.c.s

opt/pico/pico-sdk/src/rp2_common/pico_standard_link/binary_info.obj: opt/pico/pico-sdk/src/rp2_common/pico_standard_link/binary_info.c.obj
.PHONY : opt/pico/pico-sdk/src/rp2_common/pico_standard_link/binary_info.obj

# target to build an object file
opt/pico/pico-sdk/src/rp2_common/pico_standard_link/binary_info.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/opt/pico/pico-sdk/src/rp2_common/pico_standard_link/binary_info.c.obj
.PHONY : opt/pico/pico-sdk/src/rp2_common/pico_standard_link/binary_info.c.obj

opt/pico/pico-sdk/src/rp2_common/pico_standard_link/binary_info.i: opt/pico/pico-sdk/src/rp2_common/pico_standard_link/binary_info.c.i
.PHONY : opt/pico/pico-sdk/src/rp2_common/pico_standard_link/binary_info.i

# target to preprocess a source file
opt/pico/pico-sdk/src/rp2_common/pico_standard_link/binary_info.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/opt/pico/pico-sdk/src/rp2_common/pico_standard_link/binary_info.c.i
.PHONY : opt/pico/pico-sdk/src/rp2_common/pico_standard_link/binary_info.c.i

opt/pico/pico-sdk/src/rp2_common/pico_standard_link/binary_info.s: opt/pico/pico-sdk/src/rp2_common/pico_standard_link/binary_info.c.s
.PHONY : opt/pico/pico-sdk/src/rp2_common/pico_standard_link/binary_info.s

# target to generate assembly for a file
opt/pico/pico-sdk/src/rp2_common/pico_standard_link/binary_info.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/opt/pico/pico-sdk/src/rp2_common/pico_standard_link/binary_info.c.s
.PHONY : opt/pico/pico-sdk/src/rp2_common/pico_standard_link/binary_info.c.s

opt/pico/pico-sdk/src/rp2_common/pico_standard_link/crt0.obj: opt/pico/pico-sdk/src/rp2_common/pico_standard_link/crt0.S.obj
.PHONY : opt/pico/pico-sdk/src/rp2_common/pico_standard_link/crt0.obj

# target to build an object file
opt/pico/pico-sdk/src/rp2_common/pico_standard_link/crt0.S.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/opt/pico/pico-sdk/src/rp2_common/pico_standard_link/crt0.S.obj
.PHONY : opt/pico/pico-sdk/src/rp2_common/pico_standard_link/crt0.S.obj

opt/pico/pico-sdk/src/rp2_common/pico_standard_link/new_delete.obj: opt/pico/pico-sdk/src/rp2_common/pico_standard_link/new_delete.cpp.obj
.PHONY : opt/pico/pico-sdk/src/rp2_common/pico_standard_link/new_delete.obj

# target to build an object file
opt/pico/pico-sdk/src/rp2_common/pico_standard_link/new_delete.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/opt/pico/pico-sdk/src/rp2_common/pico_standard_link/new_delete.cpp.obj
.PHONY : opt/pico/pico-sdk/src/rp2_common/pico_standard_link/new_delete.cpp.obj

opt/pico/pico-sdk/src/rp2_common/pico_standard_link/new_delete.i: opt/pico/pico-sdk/src/rp2_common/pico_standard_link/new_delete.cpp.i
.PHONY : opt/pico/pico-sdk/src/rp2_common/pico_standard_link/new_delete.i

# target to preprocess a source file
opt/pico/pico-sdk/src/rp2_common/pico_standard_link/new_delete.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/opt/pico/pico-sdk/src/rp2_common/pico_standard_link/new_delete.cpp.i
.PHONY : opt/pico/pico-sdk/src/rp2_common/pico_standard_link/new_delete.cpp.i

opt/pico/pico-sdk/src/rp2_common/pico_standard_link/new_delete.s: opt/pico/pico-sdk/src/rp2_common/pico_standard_link/new_delete.cpp.s
.PHONY : opt/pico/pico-sdk/src/rp2_common/pico_standard_link/new_delete.s

# target to generate assembly for a file
opt/pico/pico-sdk/src/rp2_common/pico_standard_link/new_delete.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/opt/pico/pico-sdk/src/rp2_common/pico_standard_link/new_delete.cpp.s
.PHONY : opt/pico/pico-sdk/src/rp2_common/pico_standard_link/new_delete.cpp.s

opt/pico/pico-sdk/src/rp2_common/pico_stdio/stdio.obj: opt/pico/pico-sdk/src/rp2_common/pico_stdio/stdio.c.obj
.PHONY : opt/pico/pico-sdk/src/rp2_common/pico_stdio/stdio.obj

# target to build an object file
opt/pico/pico-sdk/src/rp2_common/pico_stdio/stdio.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/opt/pico/pico-sdk/src/rp2_common/pico_stdio/stdio.c.obj
.PHONY : opt/pico/pico-sdk/src/rp2_common/pico_stdio/stdio.c.obj

opt/pico/pico-sdk/src/rp2_common/pico_stdio/stdio.i: opt/pico/pico-sdk/src/rp2_common/pico_stdio/stdio.c.i
.PHONY : opt/pico/pico-sdk/src/rp2_common/pico_stdio/stdio.i

# target to preprocess a source file
opt/pico/pico-sdk/src/rp2_common/pico_stdio/stdio.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/opt/pico/pico-sdk/src/rp2_common/pico_stdio/stdio.c.i
.PHONY : opt/pico/pico-sdk/src/rp2_common/pico_stdio/stdio.c.i

opt/pico/pico-sdk/src/rp2_common/pico_stdio/stdio.s: opt/pico/pico-sdk/src/rp2_common/pico_stdio/stdio.c.s
.PHONY : opt/pico/pico-sdk/src/rp2_common/pico_stdio/stdio.s

# target to generate assembly for a file
opt/pico/pico-sdk/src/rp2_common/pico_stdio/stdio.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/opt/pico/pico-sdk/src/rp2_common/pico_stdio/stdio.c.s
.PHONY : opt/pico/pico-sdk/src/rp2_common/pico_stdio/stdio.c.s

opt/pico/pico-sdk/src/rp2_common/pico_stdio_uart/stdio_uart.obj: opt/pico/pico-sdk/src/rp2_common/pico_stdio_uart/stdio_uart.c.obj
.PHONY : opt/pico/pico-sdk/src/rp2_common/pico_stdio_uart/stdio_uart.obj

# target to build an object file
opt/pico/pico-sdk/src/rp2_common/pico_stdio_uart/stdio_uart.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/opt/pico/pico-sdk/src/rp2_common/pico_stdio_uart/stdio_uart.c.obj
.PHONY : opt/pico/pico-sdk/src/rp2_common/pico_stdio_uart/stdio_uart.c.obj

opt/pico/pico-sdk/src/rp2_common/pico_stdio_uart/stdio_uart.i: opt/pico/pico-sdk/src/rp2_common/pico_stdio_uart/stdio_uart.c.i
.PHONY : opt/pico/pico-sdk/src/rp2_common/pico_stdio_uart/stdio_uart.i

# target to preprocess a source file
opt/pico/pico-sdk/src/rp2_common/pico_stdio_uart/stdio_uart.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/opt/pico/pico-sdk/src/rp2_common/pico_stdio_uart/stdio_uart.c.i
.PHONY : opt/pico/pico-sdk/src/rp2_common/pico_stdio_uart/stdio_uart.c.i

opt/pico/pico-sdk/src/rp2_common/pico_stdio_uart/stdio_uart.s: opt/pico/pico-sdk/src/rp2_common/pico_stdio_uart/stdio_uart.c.s
.PHONY : opt/pico/pico-sdk/src/rp2_common/pico_stdio_uart/stdio_uart.s

# target to generate assembly for a file
opt/pico/pico-sdk/src/rp2_common/pico_stdio_uart/stdio_uart.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/opt/pico/pico-sdk/src/rp2_common/pico_stdio_uart/stdio_uart.c.s
.PHONY : opt/pico/pico-sdk/src/rp2_common/pico_stdio_uart/stdio_uart.c.s

opt/pico/pico-sdk/src/rp2_common/pico_stdlib/stdlib.obj: opt/pico/pico-sdk/src/rp2_common/pico_stdlib/stdlib.c.obj
.PHONY : opt/pico/pico-sdk/src/rp2_common/pico_stdlib/stdlib.obj

# target to build an object file
opt/pico/pico-sdk/src/rp2_common/pico_stdlib/stdlib.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/opt/pico/pico-sdk/src/rp2_common/pico_stdlib/stdlib.c.obj
.PHONY : opt/pico/pico-sdk/src/rp2_common/pico_stdlib/stdlib.c.obj

opt/pico/pico-sdk/src/rp2_common/pico_stdlib/stdlib.i: opt/pico/pico-sdk/src/rp2_common/pico_stdlib/stdlib.c.i
.PHONY : opt/pico/pico-sdk/src/rp2_common/pico_stdlib/stdlib.i

# target to preprocess a source file
opt/pico/pico-sdk/src/rp2_common/pico_stdlib/stdlib.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/opt/pico/pico-sdk/src/rp2_common/pico_stdlib/stdlib.c.i
.PHONY : opt/pico/pico-sdk/src/rp2_common/pico_stdlib/stdlib.c.i

opt/pico/pico-sdk/src/rp2_common/pico_stdlib/stdlib.s: opt/pico/pico-sdk/src/rp2_common/pico_stdlib/stdlib.c.s
.PHONY : opt/pico/pico-sdk/src/rp2_common/pico_stdlib/stdlib.s

# target to generate assembly for a file
opt/pico/pico-sdk/src/rp2_common/pico_stdlib/stdlib.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/opt/pico/pico-sdk/src/rp2_common/pico_stdlib/stdlib.c.s
.PHONY : opt/pico/pico-sdk/src/rp2_common/pico_stdlib/stdlib.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... ELF2UF2Build"
	@echo "... PioasmBuild"
	@echo "... bs2_default_bin"
	@echo "... bs2_default_padded_checksummed_asm"
	@echo "... cyw43_driver_picow_cyw43_bus_pio_spi_pio_h"
	@echo "... bs2_default"
	@echo "... main"
	@echo "... hooks.obj"
	@echo "... hooks.i"
	@echo "... hooks.s"
	@echo "... main.obj"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... opt/pico/FreeRTOS-Kernel/croutine.obj"
	@echo "... opt/pico/FreeRTOS-Kernel/croutine.i"
	@echo "... opt/pico/FreeRTOS-Kernel/croutine.s"
	@echo "... opt/pico/FreeRTOS-Kernel/event_groups.obj"
	@echo "... opt/pico/FreeRTOS-Kernel/event_groups.i"
	@echo "... opt/pico/FreeRTOS-Kernel/event_groups.s"
	@echo "... opt/pico/FreeRTOS-Kernel/list.obj"
	@echo "... opt/pico/FreeRTOS-Kernel/list.i"
	@echo "... opt/pico/FreeRTOS-Kernel/list.s"
	@echo "... opt/pico/FreeRTOS-Kernel/portable/MemMang/heap_4.obj"
	@echo "... opt/pico/FreeRTOS-Kernel/portable/MemMang/heap_4.i"
	@echo "... opt/pico/FreeRTOS-Kernel/portable/MemMang/heap_4.s"
	@echo "... opt/pico/FreeRTOS-Kernel/portable/ThirdParty/GCC/RP2040/port.obj"
	@echo "... opt/pico/FreeRTOS-Kernel/portable/ThirdParty/GCC/RP2040/port.i"
	@echo "... opt/pico/FreeRTOS-Kernel/portable/ThirdParty/GCC/RP2040/port.s"
	@echo "... opt/pico/FreeRTOS-Kernel/queue.obj"
	@echo "... opt/pico/FreeRTOS-Kernel/queue.i"
	@echo "... opt/pico/FreeRTOS-Kernel/queue.s"
	@echo "... opt/pico/FreeRTOS-Kernel/stream_buffer.obj"
	@echo "... opt/pico/FreeRTOS-Kernel/stream_buffer.i"
	@echo "... opt/pico/FreeRTOS-Kernel/stream_buffer.s"
	@echo "... opt/pico/FreeRTOS-Kernel/tasks.obj"
	@echo "... opt/pico/FreeRTOS-Kernel/tasks.i"
	@echo "... opt/pico/FreeRTOS-Kernel/tasks.s"
	@echo "... opt/pico/FreeRTOS-Kernel/timers.obj"
	@echo "... opt/pico/FreeRTOS-Kernel/timers.i"
	@echo "... opt/pico/FreeRTOS-Kernel/timers.s"
	@echo "... opt/pico/pico-sdk/src/common/pico_sync/critical_section.obj"
	@echo "... opt/pico/pico-sdk/src/common/pico_sync/critical_section.i"
	@echo "... opt/pico/pico-sdk/src/common/pico_sync/critical_section.s"
	@echo "... opt/pico/pico-sdk/src/common/pico_sync/lock_core.obj"
	@echo "... opt/pico/pico-sdk/src/common/pico_sync/lock_core.i"
	@echo "... opt/pico/pico-sdk/src/common/pico_sync/lock_core.s"
	@echo "... opt/pico/pico-sdk/src/common/pico_sync/mutex.obj"
	@echo "... opt/pico/pico-sdk/src/common/pico_sync/mutex.i"
	@echo "... opt/pico/pico-sdk/src/common/pico_sync/mutex.s"
	@echo "... opt/pico/pico-sdk/src/common/pico_sync/sem.obj"
	@echo "... opt/pico/pico-sdk/src/common/pico_sync/sem.i"
	@echo "... opt/pico/pico-sdk/src/common/pico_sync/sem.s"
	@echo "... opt/pico/pico-sdk/src/common/pico_time/time.obj"
	@echo "... opt/pico/pico-sdk/src/common/pico_time/time.i"
	@echo "... opt/pico/pico-sdk/src/common/pico_time/time.s"
	@echo "... opt/pico/pico-sdk/src/common/pico_time/timeout_helper.obj"
	@echo "... opt/pico/pico-sdk/src/common/pico_time/timeout_helper.i"
	@echo "... opt/pico/pico-sdk/src/common/pico_time/timeout_helper.s"
	@echo "... opt/pico/pico-sdk/src/common/pico_util/datetime.obj"
	@echo "... opt/pico/pico-sdk/src/common/pico_util/datetime.i"
	@echo "... opt/pico/pico-sdk/src/common/pico_util/datetime.s"
	@echo "... opt/pico/pico-sdk/src/common/pico_util/pheap.obj"
	@echo "... opt/pico/pico-sdk/src/common/pico_util/pheap.i"
	@echo "... opt/pico/pico-sdk/src/common/pico_util/pheap.s"
	@echo "... opt/pico/pico-sdk/src/common/pico_util/queue.obj"
	@echo "... opt/pico/pico-sdk/src/common/pico_util/queue.i"
	@echo "... opt/pico/pico-sdk/src/common/pico_util/queue.s"
	@echo "... opt/pico/pico-sdk/src/rp2_common/hardware_adc/adc.obj"
	@echo "... opt/pico/pico-sdk/src/rp2_common/hardware_adc/adc.i"
	@echo "... opt/pico/pico-sdk/src/rp2_common/hardware_adc/adc.s"
	@echo "... opt/pico/pico-sdk/src/rp2_common/hardware_claim/claim.obj"
	@echo "... opt/pico/pico-sdk/src/rp2_common/hardware_claim/claim.i"
	@echo "... opt/pico/pico-sdk/src/rp2_common/hardware_claim/claim.s"
	@echo "... opt/pico/pico-sdk/src/rp2_common/hardware_clocks/clocks.obj"
	@echo "... opt/pico/pico-sdk/src/rp2_common/hardware_clocks/clocks.i"
	@echo "... opt/pico/pico-sdk/src/rp2_common/hardware_clocks/clocks.s"
	@echo "... opt/pico/pico-sdk/src/rp2_common/hardware_divider/divider.obj"
	@echo "... opt/pico/pico-sdk/src/rp2_common/hardware_exception/exception.obj"
	@echo "... opt/pico/pico-sdk/src/rp2_common/hardware_exception/exception.i"
	@echo "... opt/pico/pico-sdk/src/rp2_common/hardware_exception/exception.s"
	@echo "... opt/pico/pico-sdk/src/rp2_common/hardware_gpio/gpio.obj"
	@echo "... opt/pico/pico-sdk/src/rp2_common/hardware_gpio/gpio.i"
	@echo "... opt/pico/pico-sdk/src/rp2_common/hardware_gpio/gpio.s"
	@echo "... opt/pico/pico-sdk/src/rp2_common/hardware_irq/irq.obj"
	@echo "... opt/pico/pico-sdk/src/rp2_common/hardware_irq/irq.i"
	@echo "... opt/pico/pico-sdk/src/rp2_common/hardware_irq/irq.s"
	@echo "... opt/pico/pico-sdk/src/rp2_common/hardware_irq/irq_handler_chain.obj"
	@echo "... opt/pico/pico-sdk/src/rp2_common/hardware_pll/pll.obj"
	@echo "... opt/pico/pico-sdk/src/rp2_common/hardware_pll/pll.i"
	@echo "... opt/pico/pico-sdk/src/rp2_common/hardware_pll/pll.s"
	@echo "... opt/pico/pico-sdk/src/rp2_common/hardware_sync/sync.obj"
	@echo "... opt/pico/pico-sdk/src/rp2_common/hardware_sync/sync.i"
	@echo "... opt/pico/pico-sdk/src/rp2_common/hardware_sync/sync.s"
	@echo "... opt/pico/pico-sdk/src/rp2_common/hardware_timer/timer.obj"
	@echo "... opt/pico/pico-sdk/src/rp2_common/hardware_timer/timer.i"
	@echo "... opt/pico/pico-sdk/src/rp2_common/hardware_timer/timer.s"
	@echo "... opt/pico/pico-sdk/src/rp2_common/hardware_uart/uart.obj"
	@echo "... opt/pico/pico-sdk/src/rp2_common/hardware_uart/uart.i"
	@echo "... opt/pico/pico-sdk/src/rp2_common/hardware_uart/uart.s"
	@echo "... opt/pico/pico-sdk/src/rp2_common/hardware_vreg/vreg.obj"
	@echo "... opt/pico/pico-sdk/src/rp2_common/hardware_vreg/vreg.i"
	@echo "... opt/pico/pico-sdk/src/rp2_common/hardware_vreg/vreg.s"
	@echo "... opt/pico/pico-sdk/src/rp2_common/hardware_watchdog/watchdog.obj"
	@echo "... opt/pico/pico-sdk/src/rp2_common/hardware_watchdog/watchdog.i"
	@echo "... opt/pico/pico-sdk/src/rp2_common/hardware_watchdog/watchdog.s"
	@echo "... opt/pico/pico-sdk/src/rp2_common/hardware_xosc/xosc.obj"
	@echo "... opt/pico/pico-sdk/src/rp2_common/hardware_xosc/xosc.i"
	@echo "... opt/pico/pico-sdk/src/rp2_common/hardware_xosc/xosc.s"
	@echo "... opt/pico/pico-sdk/src/rp2_common/pico_bit_ops/bit_ops_aeabi.obj"
	@echo "... opt/pico/pico-sdk/src/rp2_common/pico_bootrom/bootrom.obj"
	@echo "... opt/pico/pico-sdk/src/rp2_common/pico_bootrom/bootrom.i"
	@echo "... opt/pico/pico-sdk/src/rp2_common/pico_bootrom/bootrom.s"
	@echo "... opt/pico/pico-sdk/src/rp2_common/pico_divider/divider.obj"
	@echo "... opt/pico/pico-sdk/src/rp2_common/pico_double/double_aeabi.obj"
	@echo "... opt/pico/pico-sdk/src/rp2_common/pico_double/double_init_rom.obj"
	@echo "... opt/pico/pico-sdk/src/rp2_common/pico_double/double_init_rom.i"
	@echo "... opt/pico/pico-sdk/src/rp2_common/pico_double/double_init_rom.s"
	@echo "... opt/pico/pico-sdk/src/rp2_common/pico_double/double_math.obj"
	@echo "... opt/pico/pico-sdk/src/rp2_common/pico_double/double_math.i"
	@echo "... opt/pico/pico-sdk/src/rp2_common/pico_double/double_math.s"
	@echo "... opt/pico/pico-sdk/src/rp2_common/pico_double/double_v1_rom_shim.obj"
	@echo "... opt/pico/pico-sdk/src/rp2_common/pico_float/float_aeabi.obj"
	@echo "... opt/pico/pico-sdk/src/rp2_common/pico_float/float_init_rom.obj"
	@echo "... opt/pico/pico-sdk/src/rp2_common/pico_float/float_init_rom.i"
	@echo "... opt/pico/pico-sdk/src/rp2_common/pico_float/float_init_rom.s"
	@echo "... opt/pico/pico-sdk/src/rp2_common/pico_float/float_math.obj"
	@echo "... opt/pico/pico-sdk/src/rp2_common/pico_float/float_math.i"
	@echo "... opt/pico/pico-sdk/src/rp2_common/pico_float/float_math.s"
	@echo "... opt/pico/pico-sdk/src/rp2_common/pico_float/float_v1_rom_shim.obj"
	@echo "... opt/pico/pico-sdk/src/rp2_common/pico_int64_ops/pico_int64_ops_aeabi.obj"
	@echo "... opt/pico/pico-sdk/src/rp2_common/pico_malloc/pico_malloc.obj"
	@echo "... opt/pico/pico-sdk/src/rp2_common/pico_malloc/pico_malloc.i"
	@echo "... opt/pico/pico-sdk/src/rp2_common/pico_malloc/pico_malloc.s"
	@echo "... opt/pico/pico-sdk/src/rp2_common/pico_mem_ops/mem_ops_aeabi.obj"
	@echo "... opt/pico/pico-sdk/src/rp2_common/pico_multicore/multicore.obj"
	@echo "... opt/pico/pico-sdk/src/rp2_common/pico_multicore/multicore.i"
	@echo "... opt/pico/pico-sdk/src/rp2_common/pico_multicore/multicore.s"
	@echo "... opt/pico/pico-sdk/src/rp2_common/pico_platform/platform.obj"
	@echo "... opt/pico/pico-sdk/src/rp2_common/pico_platform/platform.i"
	@echo "... opt/pico/pico-sdk/src/rp2_common/pico_platform/platform.s"
	@echo "... opt/pico/pico-sdk/src/rp2_common/pico_printf/printf.obj"
	@echo "... opt/pico/pico-sdk/src/rp2_common/pico_printf/printf.i"
	@echo "... opt/pico/pico-sdk/src/rp2_common/pico_printf/printf.s"
	@echo "... opt/pico/pico-sdk/src/rp2_common/pico_runtime/runtime.obj"
	@echo "... opt/pico/pico-sdk/src/rp2_common/pico_runtime/runtime.i"
	@echo "... opt/pico/pico-sdk/src/rp2_common/pico_runtime/runtime.s"
	@echo "... opt/pico/pico-sdk/src/rp2_common/pico_standard_link/binary_info.obj"
	@echo "... opt/pico/pico-sdk/src/rp2_common/pico_standard_link/binary_info.i"
	@echo "... opt/pico/pico-sdk/src/rp2_common/pico_standard_link/binary_info.s"
	@echo "... opt/pico/pico-sdk/src/rp2_common/pico_standard_link/crt0.obj"
	@echo "... opt/pico/pico-sdk/src/rp2_common/pico_standard_link/new_delete.obj"
	@echo "... opt/pico/pico-sdk/src/rp2_common/pico_standard_link/new_delete.i"
	@echo "... opt/pico/pico-sdk/src/rp2_common/pico_standard_link/new_delete.s"
	@echo "... opt/pico/pico-sdk/src/rp2_common/pico_stdio/stdio.obj"
	@echo "... opt/pico/pico-sdk/src/rp2_common/pico_stdio/stdio.i"
	@echo "... opt/pico/pico-sdk/src/rp2_common/pico_stdio/stdio.s"
	@echo "... opt/pico/pico-sdk/src/rp2_common/pico_stdio_uart/stdio_uart.obj"
	@echo "... opt/pico/pico-sdk/src/rp2_common/pico_stdio_uart/stdio_uart.i"
	@echo "... opt/pico/pico-sdk/src/rp2_common/pico_stdio_uart/stdio_uart.s"
	@echo "... opt/pico/pico-sdk/src/rp2_common/pico_stdlib/stdlib.obj"
	@echo "... opt/pico/pico-sdk/src/rp2_common/pico_stdlib/stdlib.i"
	@echo "... opt/pico/pico-sdk/src/rp2_common/pico_stdlib/stdlib.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

